## NumPy
1. Numpy array is of two i.e vector and metrices.
2. Vector are the 1-D array where matrices are the 2-D array

In [1]:
import numpy as np

## 1-D Array or Vector

In [2]:
l=[1,2,3]
np.array(l)

array([1, 2, 3])

## 2-D Array or Matrices

In [3]:
l=[[1,2,3],[4,5,6]]
np.array(l)

array([[1, 2, 3],
       [4, 5, 6]])

## np.arange()
np.arange() is a function in the NumPy library that creates an array of evenly spaced values within a given range. The function takes three arguments: start, stop, and step. The resulting array includes the start value and goes up to, but does not include, the stop value, and increments by the step value. For example, np.arange(0, 10, 2) would create an array of [0, 2, 4, 6, 8].

In [4]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## np.linspace()
np.linspace() is a function in the NumPy library that creates an array of evenly spaced values over a specified interval. The function takes three arguments: start, stop and num. The resulting array will have num evenly spaced samples, calculated over the interval [start, stop]. The endpoint of the interval can optionally be included or excluded. For example, np.linspace(0, 10, 5) would create an array of [0.0, 2.5, 5.0, 7.5, 10.0].

In [5]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In the np.linspace() function, the endpoint of the interval is always included by default. However, if you want to exclude the endpoint, you can use the endpoint parameter and set it to False.

In [6]:
np.linspace(0,10,5,endpoint=False)

array([0., 2., 4., 6., 8.])

You can also use np.linspace(start,stop,num, endpoint=False, retstep=True) to return the step size as well.

In [7]:
np.linspace(0,10,5,retstep=True)

(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), 2.5)

## np.random.rand()
np.random.rand() is a function from the NumPy library that generates random numbers from a uniform distribution. The function generates random numbers from a continuous interval between 0 and 1.

In [8]:
np.random.rand(2,5)

array([[0.94990216, 0.84081077, 0.6121987 , 0.95608786, 0.25021745],
       [0.41762226, 0.35953059, 0.93652498, 0.48933003, 0.72243962]])

## np.random.randn()
np.random.randn() is a function from the NumPy library that generates random numbers from a standard normal distribution, also known as a Gaussian distribution. The standard normal distribution is a normal distribution with a mean of 0 and a standard deviation of 1.

In [9]:
np.random.randn(1,2)

array([[ 1.70511762, -0.92431324]])

## np.random.randint()
np.random.randint() is a function from the NumPy library that generates random integers from a given range. The function takes in three arguments:

low: The lower bound of the range (inclusive).
high: The upper bound of the range (exclusive).
size: The shape of the output array. It can be an integer or a tuple of integers.

In [10]:
print(np.random.randint(0,50))
print(np.random.randint(0,50,size=2))
print(np.random.randint(0,50,size=(2,2)))

25
[38 34]
[[22 39]
 [18 12]]


## Numpy Array Operation

In [11]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])

In [12]:
arr.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
arr.max()

10

In [14]:
arr.min()

1

In [15]:
# Max value index
arr.argmax()

9

In [16]:
# Min Value index
arr.argmin()

0

In [17]:
arr.shape

(10,)

In [18]:
arr.dtype

dtype('int32')

In [19]:
np.random.randint(arr)

array([0, 1, 1, 0, 1, 0, 6, 1, 2, 6])

In [20]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Indexing and Slicing

In [21]:
arr=np.array([4,4,5,1,2,3,8,10])

In [22]:
arr_2d=np.array([[10,11,15],[20,25,28],[32,45,67]])

In [23]:
slice_arr_2d=arr_2d[0:2,0:2]
print(slice_arr_2d)

[[10 11]
 [20 25]]


In [24]:
slice_arr_2d[0:2,0:2]=100

In [25]:
slice_arr_2d

array([[100, 100],
       [100, 100]])

In [26]:
arr_2d

array([[100, 100,  15],
       [100, 100,  28],
       [ 32,  45,  67]])

In [27]:
arr_2d[1:,0:]

array([[100, 100,  28],
       [ 32,  45,  67]])

In [28]:
arr_2d>80

array([[ True,  True, False],
       [ True,  True, False],
       [False, False, False]])

In [29]:
arr_2d=np.arange(50).reshape(5,10)

In [30]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [31]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [32]:
arr_2d[arr_2d>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49])

In [33]:
arr_2d>20

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

## NumPy Operations
 ### .Array with Array
 ### .Array with Scalars
 ### .Universal Array Functions

In [34]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [36]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [38]:
arr/arr

C:\Users\Himanshu Dhawan\AppData\Local\Temp\ipykernel_7644\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [39]:
arr.max()

10

In [40]:
arr.min()

0

In [41]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [42]:
arr*100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])